name: Get Unity License 💡

on: 
  workflow_dispatch:

jobs:
  activation:
    name: Request Manual Activation File (.alf)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Request activation file
        uses: game-ci/unity-request-activation-file@v2.3 # تحديث الإصدار
        id: get-alf
        # ملاحظة: في النسخ الجديدة تم دمج المتغيرات تلقائياً
        # إذا استمر الخطأ، اترك خانة with فارغة وسيكتشف النسخة من ProjectSettings

      - name: Upload .alf file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000_Activation
          path: ${{ steps.get-alf.outputs.filePath }}
