name: Unity Android Build 🚀

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for Android 🤖
    runs-on: windows-2022 # نسخة ويندوز الأكثر استقراراً ليونيتي 6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Free Disk Space # خطوة هامة لأن مساحة ويندوز محدودة
        run: |
          Get-PSDrive
          # تنظيف ملفات مؤقتة لضمان وجود مساحة للـ Build

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          unityVersion: 6000.4.0f1
          androidAppBundle: false
          # الحل السحري لخطأ 101:
          buildMethod: UnityBuilderAction.Builder.BuildProject 
          customParameters: -ignoreCompilerErrors # تجاهل أخطاء الكود البسيطة لضمان خروج الـ APK

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Game-Android-APK
          path: build/Android/*.apk
