name: Unity Android CI 🚀

on: workflow_dispatch

jobs:
  build:
    name: Build Android 📱
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Cache Library
      uses: actions/cache@v3
      with:
        path: Library
        key: Library-Android
        restore-keys: |
          Library-

    - name: Build APK
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        unityVersion: 6000.4.0f1
        targetPlatform: Android
        androidAppBundle: false
        buildName: MyGame
        buildsPath: build
        # إعدادات التوقيع باستخدام الملف الذي ولدته
        androidKeystoreName: ali_world.keystore
        androidKeystorePass: "اكتب_كلمة_السر_هنا"
        androidKeyaliasName: ali_dev
        androidKeyaliasPass: "اكتب_كلمة_السر_هنا"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Android-APK
        path: build/Android/*.apk
