name: Unity iOS Structure Build 🚀

on: [workflow_dispatch, push]

jobs:
  build:
    name: Build iOS Project 🍏
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      # 1. بناء المشروع بواسطة Unity (بدون توقيع)
      - name: Unity - Builder
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: iOS
          version: 6000.4.0f1

      # 2. ضغط هيكل Xcode الناتج
      - name: Zip Xcode Project 📦
        run: |
          zip -r Xcode_Project.zip build/iOS

      # 3. رفع الملف الناتج لـ GitHub
          # هذا الملف هو ما سنستخدمه للتثبيت
      - name: Upload Artifact 🚀
        uses: actions/upload-artifact@v4
        with:
          name: Unity-Xcode-Output
          path: Xcode_Project.zip
